services:
  odoo:
    build: .
    networks:
      - net_odoo
    container_name: ${ODOO_CONTAINER_NAME}
    depends_on:
      - db_odoo
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_DEBUG_PORT}:3000"
    command: >
      /usr/bin/python3 -m debugpy --listen 0.0.0.0:3000 /usr/bin/odoo
      -u new_module
      --load-language=es_ES
      --config=/mnt/environment/confs/odoo.conf
    volumes:
      - /volumes/filestore:/opt/odoo/odoo-data
      - "data_dir:/var/lib/odoo"
      - ./environment:/mnt/environment
      - ./../code:/mnt/code
    restart: always
    init: true

  db_odoo:
    image: ${DB_IMAGE}
    networks:
      - net_odoo
    container_name: ${ODOO_DB_CONTAINER_NAME}
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}

volumes: 
  data_dir:

networks:
  net_odoo:
